### ISSUE TITLE
Project inquiry

### ISSUE THREAD

**Issue by caseymilne** [Njengah/njengah#1]
I have a project that might be a good fit for you Joe. It's a WordPress plugin that provides a couple of Gutenberg blocks for registration... I need some PHP handling for cleaning up user accounts that never activate so it involves a meta query. 

I tried to contact you via your website but the form never finishes processing after submission... no visible errors but the ajax spinner just spins forever without submitting the form. 

You can reach me at casey AT saberwp.com or visit our site at saberwp.com. 

Thanks, hope to hear from you soon and have a good day. 

PS. I found your site after searching for some sample code on axios/react form submission.

**Comment by Njengah** [comment]
Hello Casey,

Sorry to hear you tried reaching me but you could not. I will check that form and advice. 

I can help you with that project. 

Kindly let me know. 

Joe

**Comment by caseymilne** [comment]
I just found this today by chance it appeared in my feed... I will email you soon! Thanks for the reply.
